name: PHPCS checks (Docker Alternative)
on:
  push
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  phpcs_docker_alternative:
    name: PHPCS (Docker Alternative)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v3
        id: cache-composer
        with:
          path: vendor
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}
      - name: Composer install
        if: steps.cache-composer.outputs.cache-hit != 'true'
        run: composer install
      - name: Run PHPCS checks
        run: |
          docker run --rm \
            -v "${GITHUB_WORKSPACE}:/app" \
            --workdir "/app" \
            php:7-cli \
            bash -c "php -d memory_limit=1G /app/vendor/bin/phpcs -s --standard=/app/.phpcs.xml.dist"